# Generated by Django 4.0.6 on 2022-07-07 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_book_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='name',
            new_name='title',
        ),
    ]
