# Generated by Django 4.0.6 on 2022-07-07 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_rename_name_book_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='book',
            name='date',
        ),
    ]
